
// Specifying class names, mainly used for triggering animations 
// and values
const PAGE_LOAD_DELAY = 2500, 
	MIN_SCROLL_DOWN_PERCENTAGE = 40, 
	MIN_SCROLL_DOWN = $( window ).height() * ( MIN_SCROLL_DOWN_PERCENTAGE / 100 ),
	FLOATING_BUTTON_TIME_VISIBLE = 1000, 
	BUTTON_CLASS = "button", 
	OPEN_NAV_BUTTON_TEXT = "Menu", 
	CLOSE_NAV_BUTTON_TEXT = "Close navigation", 
	BUTTON_FLOATING_TEXT = OPEN_NAV_BUTTON_TEXT,
	OPEN_NAV_BUTTON_CLASS = "open-nav-button", 
	CLOSE_NAV_BUTTON_CLASS = "close-nav-button",
	CLOSE_BUTTON_PREVIEW_CLASS = "close-button-preview", 
	CLOSE_BUTTON_PREVIEW_VISIBLE_CLASS = "close-button-preview-visible", 
	BUTTON_FLOATING_CLASS = "floating-button", 
	BUTTON_FLOATING_VISIBLE_CLASS = "visible", 
	FLOATING_NAV_INITIAL_LABEL = "Menu", 
	CURRENT_LINK_CLASS = "current-link", 
	PREVIEW_VISIBLE_CLASS = "preview-visible", 
	LABEL_CLASS = "label",
	LABEL_INITIAL_CLASS = "label-enter", 
	LABEL_VISIBLE_CLASS = "label-visible", 
	LABEL_TEXT = "Menu",
	NAV_OPEN_CLASS = "nav-open", 
	NAV_CLOSE_CLASS = "nav-close", 
	NAV_COPY_CLASS = "main-nav-copy";