const floatingNavSettings = {

	BUTTON_CLASS: SETTINGS.BUTTON_CLASS, 
	
	FLOATING_NAV_CLASS: "floating-nav", 
	NAV_OPEN_CLASS: "nav-open", 
	NAV_CLOSE_CLASS: "nav-close", 

	NAV_LINKS_WRAPPER_CLASS: "nav-links-wrapper", 
	NAV_WRAPPER_CLASS: "nav-wrapper", 
	
	BUTTON_FLOATING_CLASS: "floating-button", 
	BUTTON_FLOATING_TEXT: "Menu", 
	BUTTON_FLOATING_VISIBLE_CLASS: "button-visible", 

	MIN_SCROLL_DOWN_PERCENTAGE: 40, 
	MIN_SCROLL_DOWN: $( window ).height() * ( SETTINGS.MIN_SCROLL_DOWN_PERCENTAGE / 100 ),
	BUTTON_FLOATING_TIME_VISIBLE: 1000, 

	BUTTON_CLOSE_CLASS: "close-nav-button", 
	BUTTON_CLOSE_TEXT: "Close Navigation", 
	
	LABEL_CLASS: "label", 
	LABEL_VISIBLE_CLASS: "label-visible", 
	LABEL_WRAPPER_CLASS: "label-wrapper", 
	MENU_LABEL_CLASS: "menu-label", 
	MENU_LABEL_TEXT: "Menu", 
	MENU_LABEL_INITIAL_CLASS: "menu-label-enter", 
	CLOSE_BUTTON_LABEL_CLASS: "close-button-label", 
	LINK_LABEL_CLASS: "link-label", 
	LINK_CLASS: SETTINGS.LINK_CLASS, 
	LINK_CURRENT_CLASS: SETTINGS.LINK_CURRENT_CLASS
}; 
	
	/* BUILDING: {
		CLASSES: {
			FLOATING_NAV_CLASS: "floating-nav",
			LABEL_WRAPPER_CLASS = "label-wrapper", 
			NAV_LINKS_WRAPPER_CLASS = "nav-links-wrapper", 
			NAV_WRAPPER_CLASS = "nav-wrapper", 
			BUTTON_CLASS: SETTINGS.BUTTON.BUTTON_CLASS, 
			BUTTON_FLOATING_CLASS: "floating-button", 
			CLOSE_BUTTON_CLASS: "close-nav-button", 
			LABEL_CLASS: "label", 
			MENU_LABEL_CLASS: "menu-label", 
			LINK_LABEL_CLASS: "link-label", 
			CLOSE_BUTTON_LABEL_CLASS: "close-button-label"
		
		}, 
		
		TEXT: {
			BUTTON_FLOATING_TEXT: SETTINGS.MAIN_NAV.OPEN_NAV_BUTTON.OPEN_NAV_BUTTON_TEXT, 
			CLOSE_BUTTON_TEXT: "Close navigation", 
			MENU_LABEL_TEXT: "Menu" 
			
		}
	
	}, 
	
	FUNCTIONALITY: {
		CLASSES: {
			NAV_OPEN_CLASS: "nav-open", 
			NAV_CLOSE_CLASS: "nav-close", 
			BUTTON_FLOATING_VISIBLE_CLASS: "visible", 
			LINK_CURRENT_CLASS: SETTINGS.LINK.LINK_CURRENT_CLASS, 
			LABEL_VISIBLE_CLASS: "label-visible", 
			MENU_LABEL_INITIAL_CLASS: "label-enter"
		}, 
		
		BUTTON_FLOATING_DISPLAY_SETTINGS: { 
			MIN_SCROLL_DOWN_PERCENTAGE: 40, 
			MIN_SCROLL_DOWN: $( window ).height() * ( SETTINGS.PAGE.MIN_SCROLL_DOWN_PERCENTAGE / 100 ),
			TIME_VISIBLE: 1000
		}
		
	} */
	
	
	
	
	
	
	
	
	
	/* FLOATING_NAV_CLASS: "floating-nav", 
	NAV_OPEN_CLASS: "nav-open", 
	NAV_CLOSE_CLASS: "nav-close", 
	
	BUTTON_FLOATING: {
		BUTTON_FLOATING_CLASS: "floating-button", 
		BUTTON_FLOATING_VISIBLE_CLASS: "visible", 
		BUTTON_FLOATING_TEXT: MAIN_NAV.OPEN_NAV_BUTTON.OPEN_NAV_BUTTON_TEXT, 
		
		DISPLAY_SETTINGS: { 
			MIN_SCROLL_DOWN_PERCENTAGE: 40, 
			MIN_SCROLL_DOWN: $( window ).height() * ( PAGE.MIN_SCROLL_DOWN_PERCENTAGE / 100 ),
			TIME_VISIBLE: 1000
		}
		
	}, 
	
	CLOSE_BUTTON: {
		CLOSE_BUTTON_CLASS: "close-nav-button",
		CLOSE_BUTTON_TEXT: "Close navigation", 
	}, 
	
	LABELS: {
		LABEL_CLASS: "label",
		LABEL_VISIBLE_CLASS: "label-visible", 
		
		MENU: {
			MENU_LABEL_CLASS: "menu-label", 
			MENU_LABEL_INITIAL_CLASS: "label-enter", 
			MENU_LABEL_TEXT: "Menu"
		}, 
		
		LINK: { 
			LINK_LABEL_CLASS: "link-label"
		}, 
		
		CLOSE_BUTTON: {
			CLOSE_BUTTON_LABEL_CLASS: "close-button-label"
			
		}
	} */

/* const FLOATING_NAV_BUILDING = {
	LABELS: FLOATING_NAV_SETTINGS.LABELS, 
	
	BUTTON_CLASSES: {
		BUTTON_CLASS: FLOATING_NAV_SETTINGS.STRUCTURE.CLASSES.BUTTON_CLASS, 
		BUTTON_FLOATING_CLASS: FLOATING_NAV_SETTINGS.BUTTON_FLOATING.STRUCTURE.CLASSES.BUTTON_FLOATING_CLASS, 
		CLOSE_BUTTON_CLASS: FLOATING_NAV_SETTINGS.BUTTON_CLOSE.STRUCTURE.CLASSES.BUTTON_CLOSE_CLASS 
	}
	
	FLOATING_NAV_CLASSES: FLOATING_NAV_SETTINGS.FLOATING_NAV.STRUCTURE.CLASSES,   
	
	LABEL_CLASSES: { 
		LABEL_WRAPPER_CLASS: LABELS.ELEMENTS.LABEL_WRAPPER.STRUCTURE.CLASSES.LABEL_WRAPPER_CLASS, 
		MENU_LABEL_CLASS: LABELS.ELEMENTS.MENU_LABEL.STRUCTURE.CLASSES.MENU_LABEL_CLASS, 
		CLOSE_BUTTON_LABEL_CLASS: LABELS.ELEMENTS.CLOSE_BUTTON_LABEL.STRUCTURE.CLASSES.CLOSE_BUTTON_LABEL_CLASS, 
		LINK_LABEL_CLASS: LABELS.ELEMENTS.LINK_LABEL.STRUCTURE.CLASSES.LINK_LABEL_CLASS
	}
	
} */




















